name: seenet
description: SeeNet Flutter App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10
  get: ^4.7.2
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.8
  firebase_core: ^2.30.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/logo.svg
    - assets/images/snail.svg
    - assets/images/iptv.svg
    - assets/images/app.svg
    - assets/images/repair.svg